travis:
  secure:
    BINSTAR_TOKEN: V43AI4V30Zxx9oKanOtJ2rllCbz5N5ESJBZTD91vUSjYwWy3FttVlCcH6wGiWTOpvwsVpK8imvD7WFhhJG66OucMubi4gu/jKYm1Jv/BDk2xBFV3ew5Nqc3YGWbszLdW0R+TKacgd3a8mv7ayUTL6zPyw7cbYuy5LTXPY64a1VaNAGhVLYVUhGFTMCtuJZ5u2eXCmkJ0rRi2AqhFhfIhQjPz6dziEOZNlqf5NgaUBwPJV8PZNg4JyBPBerDTfR7CQl1U29DV5q05xI9foNrFyjpO5FcgPCcY70u7Sjt4Jn5AAQRv1VJQAd07uQ3mt07S07pXxn+VBxwn/lDEjLBo8d/D7UDhfhCK7dordjGIu3XaNRR5llJp8ARXJTGiLbYH/S0hcnIyA/WqqmG7ct9c4T7NO+FuZ3mseOKTuCaqt9VIb3ltdgO8Uugu+KwRa9Tgr8KRr1hTNJ+YxSGivkqah3BPvhSaU7eIrvRxGKfrTc908qtaGsCZb42p62XkRQZ7L2mQzl+AgGuQCZWolB++aHBB1N52huVBe2elQij4LrKsDWR/UIT3LIjS3HbTYXlspsue3GALe92Bn4jJs29E7Osju0uHwbyqsh5YBTotp2D8mr0JWwF5Cgsc3QtoZNJ+PfvW6gcpwEdzccv69PVhjqf4dJjVRpOABsEw2JEWwsM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
