travis:
  secure:
    BINSTAR_TOKEN: MB0LlDrXpm6Bp1r3dorbXwTNxfmxjfB40cv50tKOCkBHNFusBZVFzR2ax3WQp7JvEk0GqzhfAumU0/lAJ+/wDHgTqmOYaiKtfPNo0b+ib9MdOAmtpysMZRqAR7JdojO1YhIszoPN6c1cB5AqcGzZv9kdSfmK44Fmu3EN5nUO4/Klt4TikjVoch/W/BNSXS0o6dcsrF41jnS6xVbBPQ36QVnsSCUHYkwuetIDK4Cd7wxnHIKFuNT6czClOw05W5WHpp3Jooa7AYzkq6Ull3tHmmpXg8/a+Ow42xlzyhXYTmEdecM+tl6FodHfL/pURWhKJzuRMAMpSnzsTKXK47RYeBhyMPDlUmhhW1qtBQef7fLku+hmh2anAS+0riX6rY6pTot9YwAvtptX7ezcjRBz4Vex59oDQFHe3l2qUD/kTiPPjY3bV3g2ikoU2BnmUBhIukHkYbEqbn6EI3BHHhReD2sZQPqcDNA8aCzER4gv75bznfmm28bgL3n2JyIiB9L6FSPPb9dXHIaLp6AWzy+hTgnjeNmZ3mKYr2SiZqj5iQ9WmmnoUMC+UwP13fHSna2y5C7ptnDMXMPJMzXvmobmmZrFQxbsdl8ACc368pknHA5WRJIUV3JHcGKSrx31GnbYVmwntOP75ZgQqG1qqd1KBoAIpAAfzZMhbt7yb6OC9WY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
